name: Publish Python Package to PyPI

on:
  # Déclenche l'action quand un tag Git commençant par 'v' est poussé
  push:
    tags:
      - 'v*'
  # Permet de lancer manuellement le workflow depuis l'interface GitHub
  workflow_dispatch:

# Utilise OIDC pour une publication sécurisée sans stocker de secrets
permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nécessaire pour les outils de versioning dynamiques

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up uv (gestionnaire de paquets rapide)
        uses: astral-sh/setup-uv@v1

      - name: Create and activate virtual environment
        run: |
          uv venv .venv
          source .venv/bin/activate
          
      - name: Install build dependencies
        run: |
          source .venv/bin/activate
          uv pip install build

      - name: Build package
        run: |
          source .venv/bin/activate
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
